# One Hot Encoding...

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("dataset/car data.csv")
df.head()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0

In [3]:
df.shape

(301, 9)

In [4]:


print(df['Car_Name'].value_counts())
df['Fuel_Type'].value_counts()

city                        26
corolla altis               16
verna                       14
fortuner                    11
brio                        10
                            ..
Honda CB Trigger             1
Yamaha FZ S                  1
Bajaj Pulsar 135 LS          1
Activa 4g                    1
Bajaj Avenger Street 220     1
Name: Car_Name, Length: 98, dtype: int64


Petrol    239
Diesel     60
CNG         2
Name: Fuel_Type, dtype: int64

In [5]:
#checking uniqe cars brand

df['Car_Name'].nunique()

98

# One hot encoding using pandas

Applying one hot encoding in **Fuel_Type** and **Transmission** colums.

In [6]:
df_encoded = pd.get_dummies(df,columns=['Fuel_Type','Transmission'])
df_encoded    

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Seller_Type  \
0       ritz  2014           3.35           5.59       27000      Dealer   
1        sx4  2013           4.75           9.54       43000      Dealer   
2       ciaz  2017           7.25           9.85        6900      Dealer   
3    wagon r  2011           2.85           4.15        5200      Dealer   
4      swift  2014           4.60           6.87       42450      Dealer   
..       ...   ...            ...            ...         ...         ...   
296     city  2016           9.50          11.60       33988      Dealer   
297     brio  2015           4.00           5.90       60000      Dealer   
298     city  2009           3.35          11.00       87934      Dealer   
299     city  2017          11.50          12.50        9000      Dealer   
300     brio  2016           5.30           5.90        5464      Dealer   

     Owner  Fuel_Type_CNG  Fuel_Type_Diesel  Fuel_Type_Petrol  \
0        0              0                 0                 1   
1        0              0                 1                 0   
2        0              0                 0                 1   
3        0              0                 0                 1   
4        0              0                 1                 0   
..     ...            ...               ...               ...   
296      0              0                 1                 0   
297      0              0                 0                 1   
298      0              0                 0                 1   
299      0              0                 1                 0   
300      0              0                 0                 1   

     Transmission_Automatic  Transmission_Manual  
0                         0                    1  
1                         0                    1  
2                         0                    1  
3                         0                    1  
4                         0                    1  
..                      ...                  ...  
296                       0                    1  
297                       0                    1  
298                       0                    1  
299                       0                    1  
300                       0                    1  

[301 rows x 12 columns]

In [7]:
df_encoded.shape

(301, 12)

# K - 1 One Hot Encoding

In [8]:
df_encoded = pd.get_dummies(df,columns=['Fuel_Type','Transmission'],drop_first=True)
df_encoded

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Seller_Type  \
0       ritz  2014           3.35           5.59       27000      Dealer   
1        sx4  2013           4.75           9.54       43000      Dealer   
2       ciaz  2017           7.25           9.85        6900      Dealer   
3    wagon r  2011           2.85           4.15        5200      Dealer   
4      swift  2014           4.60           6.87       42450      Dealer   
..       ...   ...            ...            ...         ...         ...   
296     city  2016           9.50          11.60       33988      Dealer   
297     brio  2015           4.00           5.90       60000      Dealer   
298     city  2009           3.35          11.00       87934      Dealer   
299     city  2017          11.50          12.50        9000      Dealer   
300     brio  2016           5.30           5.90        5464      Dealer   

     Owner  Fuel_Type_Diesel  Fuel_Type_Petrol  Transmission_Manual  
0        0                 0                 1                    1  
1        0                 1                 0                    1  
2        0                 0                 1                    1  
3        0                 0                 1                    1  
4        0                 1                 0                    1  
..     ...               ...               ...                  ...  
296      0                 1                 0                    1  
297      0                 0                 1                    1  
298      0                 0                 1                    1  
299      0                 1                 0                    1  
300      0                 0                 1                    1  

[301 rows x 10 columns]

# One Hot Encoding with Sklearn

In [9]:
df.head()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0

**Spliting X and Y**

In [36]:
x = df[['Present_Price','Kms_Driven','Fuel_Type','Transmission']]

y = df['Selling_Price']

In [37]:
#Training and Testing the data

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.20,random_state=1)

In [38]:
x_train.head()

Present_Price  Kms_Driven Fuel_Type Transmission
102           1.78        4000    Petrol       Manual
80           14.89       23000    Diesel       Manual
245           9.40       71000    Diesel       Manual
163           0.95       27000    Petrol       Manual
131           0.82       18000    Petrol       Manual

**Appling Sklearn OneHot Encoding**

In [25]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

In [43]:
x_train_new = ohe.fit_transform(x_train[['Fuel_Type','Transmission']]).toarray()
x_test_new = ohe.transform(x_test[['Fuel_Type','Transmission']]).toarray()

In [44]:
x_train_new

array([[0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 1.],
       ...,
       [0., 0., 1., 0., 1.],
       [0., 0., 1., 0., 1.],
       [0., 0., 1., 0., 1.]])

Transform x and y is a numpuy array,thats whay we should x and y others columns in numpuy array then we will add them togather.

In [50]:
#Converting in numpuy array

x_train[['Present_Price','Kms_Driven']].values

array([[1.78000e+00, 4.00000e+03],
       [1.48900e+01, 2.30000e+04],
       [9.40000e+00, 7.10000e+04],
       [9.50000e-01, 2.70000e+04],
       [8.20000e-01, 1.80000e+04],
       [7.98000e+00, 6.20000e+04],
       [6.40000e-01, 1.37000e+04],
       [1.86100e+01, 6.20000e+04],
       [5.10000e-01, 3.20000e+04],
       [1.18000e+01, 9.01000e+03],
       [1.07900e+01, 4.30000e+04],
       [1.86100e+01, 7.20000e+04],
       [5.40000e-01, 1.40000e+04],
       [2.40000e+00, 7.00000e+03],
       [7.15000e+00, 5.80000e+04],
       [3.45000e+00, 1.65000e+04],
       [1.36000e+01, 1.09800e+04],
       [9.83000e+00, 2.07100e+03],
       [6.40000e+00, 1.90000e+04],
       [3.76000e+00, 1.00790e+04],
       [1.78000e+00, 6.00000e+03],
       [2.04500e+01, 5.90000e+04],
       [1.47900e+01, 1.29000e+04],
       [1.50000e+00, 1.80000e+04],
       [8.06000e+00, 4.50000e+04],
       [4.60000e+00, 2.25170e+04],
       [8.70000e-01, 1.50000e+04],
       [8.00000e-01, 7.00000e+03],
       [8.10000e+00,

In [52]:
#Adding two numpy array

np.hstack((x_train[['Present_Price','Kms_Driven']].values,x_train_new))


array([[1.7800e+00, 4.0000e+03, 0.0000e+00, ..., 1.0000e+00, 0.0000e+00,
        1.0000e+00],
       [1.4890e+01, 2.3000e+04, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00],
       [9.4000e+00, 7.1000e+04, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00],
       ...,
       [1.8610e+01, 5.6001e+04, 0.0000e+00, ..., 1.0000e+00, 0.0000e+00,
        1.0000e+00],
       [9.4000e+00, 1.5141e+04, 0.0000e+00, ..., 1.0000e+00, 0.0000e+00,
        1.0000e+00],
       [2.2800e+00, 1.2700e+05, 0.0000e+00, ..., 1.0000e+00, 0.0000e+00,
        1.0000e+00]])

# One Hot Encoding with Top Categories

In [54]:

count = df['Car_Name'].value_counts()
count

city                        26
corolla altis               16
verna                       14
fortuner                    11
brio                        10
                            ..
Honda CB Trigger             1
Yamaha FZ S                  1
Bajaj Pulsar 135 LS          1
Activa 4g                    1
Bajaj Avenger Street 220     1
Name: Car_Name, Length: 98, dtype: int64

In [59]:
count.nunique()

14

In [63]:
moreThan_10 = 10
rep  = count[count<=moreThan_10].index
rep

Index(['brio', 'ciaz', 'innova', 'i20', 'grand i10', 'jazz', 'amaze',
       'Royal Enfield Classic 350', 'ertiga', 'eon', 'sx4', 'alto k10', 'i10',
       'swift', 'Bajaj Pulsar 150', 'Royal Enfield Thunder 350', 'ritz',
       'wagon r', 'etios liva', 'dzire', 'xcent', 'etios cross',
       'Royal Enfield Thunder 500', 'TVS Apache RTR 160', 'Yamaha FZ S V 2.0',
       'creta', 'Honda CB Hornet 160R', 'etios g', 'Bajaj Avenger 220',
       'Bajaj Pulsar NS 200', 'Bajaj Discover 125', 'Bajaj Pulsar 220 F',
       'TVS Apache RTR 180', 'Yamaha FZ  v 2.0', 'Honda Activa 4G',
       'Hero Extreme', 'Honda CB twister', 'Hero Splender iSmart', 'Activa 3g',
       'Hero Passion Pro', 'Honda CB Shine', 'Bajaj Avenger 220 dtsi',
       'Honda CBR 150', 'elantra', 'Royal Enfield Classic 500', 'KTM RC200',
       'Honda Karizma', 'Bajaj  ct 100', 'Hero  Ignitor Disc', 'TVS Jupyter',
       'Hero Honda Passion Pro', 'Hero Splender Plus', 'vitara brezza',
       'Bajaj Discover 100', 'Suzuki Acces

In [64]:
pd.get_dummies(df['Car_Name'].replace(rep,'uncommon'))

city  corolla altis  fortuner  uncommon  verna
0       0              0         0         1      0
1       0              0         0         1      0
2       0              0         0         1      0
3       0              0         0         1      0
4       0              0         0         1      0
..    ...            ...       ...       ...    ...
296     1              0         0         0      0
297     0              0         0         1      0
298     1              0         0         0      0
299     1              0         0         0      0
300     0              0         0         1      0

[301 rows x 5 columns]